#!/bin/zsh

if [ ! -f "$HOME/.antigen/antigen.zsh" ]; then
  if [ "$(command -v curl)" ]; then
    curl -fsSL https://git.io/antigen --create-dirs -o "$HOME/.antigen/antigen.zsh"
  elif [ "$(command -v wget)" ]; then
    mkdir -p "$HOME/.antigen"
    wget -q https://git.io/antigen -o "$HOME/.antigen/antigen.zsh"
  else
    echo "Not able to install Antigen since we have no curl or wget." >&2
  fi
fi

if [ -f "$HOME/.antigen/antigen.zsh" ]; then
  source "$HOME/.antigen/antigen.zsh"
else
  # Does not load Antigen if it was not succesfully installed
  return
fi

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  # Bundles from the default repo (robbyrussell's oh-my-zsh)
  git
  git-extras
  z
  docker
  docker-compose
  helm
  kubectl
  heroku
  pip
  lein
  npm
  node
  command-not-found
  common-aliases

  # Syntax highlighting bundle.
  zsh-users/zsh-syntax-highlighting

  # Fish-like auto suggestions
  zsh-users/zsh-autosuggestions

  # Extra zsh completions
  zsh-users/zsh-completions

  # Node Version Manager
  lukechilds/zsh-nvm
EOBUNDLES

# Load the theme.
# antigen theme denysdovhan/spaceship-prompt
antigen theme romkatv/powerlevel10k

# Tell Antigen that you're done.
antigen apply
