#!/usr/bin/env bash

echo_task() {
  printf "\033[0;34m--> %s\033[0m\n" "$@"
}

set -euo pipefail

if [ ! "$(command -v chezmoi)" ]; then
  bin_dir="$HOME/.local/bin"
  chezmoi="$bin_dir/chezmoi"
  echo_task "Installing chezmoi to $chezmoi"
  sh -c "$(wget -qO- https://git.io/chezmoi)" -- -b "$bin_dir"
else
  chezmoi=$(which chezmoi)
fi

echo_task "Initializing chezmoi"
script_dir="$(cd "${BASH_SOURCE[0]%/*}" && pwd)"
cmd="$chezmoi init --apply --source $script_dir"
echo "$cmd"
# shellcheck disable=SC2086
exec $cmd
