{{ $ohMyZshRevision := output "bash" "-c" "git ls-remote https://github.com/ohmyzsh/ohmyzsh.git HEAD | awk '{ print $1}'" | trim }}
".oh-my-zsh":
  type: archive
  url: "https://github.com/ohmyzsh/ohmyzsh/archive/{{ $ohMyZshRevision }}.tar.gz"
  exact: true
  stripComponents: 1

{{ $powerlevel10kRevision := output "bash" "-c" "git ls-remote https://github.com/romkatv/powerlevel10k.git HEAD | awk '{ print $1}'" | trim }}
".oh-my-zsh/custom/themes/powerlevel10k":
  type: archive
  url: "https://github.com/romkatv/powerlevel10k/archive/{{ $powerlevel10kRevision }}.tar.gz"
  exact: true
  stripComponents: 1

{{ $zshSyntaxHighlightingRevision := output "bash" "-c" "git ls-remote https://github.com/zsh-users/zsh-syntax-highlighting.git HEAD | awk '{ print $1}'" | trim }}
".oh-my-zsh/custom/plugins/zsh-syntax-highlighting":
  type: archive
  url: "https://github.com/zsh-users/zsh-syntax-highlighting/archive/{{ $zshSyntaxHighlightingRevision }}.tar.gz"
  exact: true
  stripComponents: 1

{{ $zshAutoSuggestionsRevision := output "bash" "-c" "git ls-remote https://github.com/zsh-users/zsh-autosuggestions.git HEAD | awk '{ print $1}'" | trim }}
".oh-my-zsh/custom/plugins/zsh-autosuggestions":
  type: archive
  url: "https://github.com/zsh-users/zsh-autosuggestions/archive/{{ $zshAutoSuggestionsRevision }}.tar.gz"
  exact: true
  stripComponents: 1

{{ $zshCompletionsRevision := output "bash" "-c" "git ls-remote https://github.com/zsh-users/zsh-completions.git HEAD | awk '{ print $1}'" | trim }}
".oh-my-zsh/custom/plugins/zsh-completions":
  type: archive
  url: "https://github.com/zsh-users/zsh-completions/archive/{{ $zshCompletionsRevision }}.tar.gz"
  exact: true
  stripComponents: 1

{{ if not .is_devcontainer -}}
{{   if .is_gnome | and (not .is_wsl) -}}
{{ $extensionInstallerRevision := output "git" "ls-remote" "https://github.com/brunelli/gnome-shell-extension-installer.git" "HEAD" | trimSuffix "HEAD\n" | trim }}
".local/bin/gnome-shell-extension-installer":
  type: file
  url: "https://raw.githubusercontent.com/brunelli/gnome-shell-extension-installer/{{ $extensionInstallerRevision }}/gnome-shell-extension-installer"
  executable: true
{{-  end }}

{{ $dockerComposeVersion := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/docker/compose/releases/latest" | trim | base -}}
".docker/cli-plugins/docker-compose":
  type: file
  url: "https://github.com/docker/compose/releases/download/{{ $dockerComposeVersion }}/docker-compose-linux-x86_64"
  executable: true

{{ $dockerBuildxVersion := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/docker/buildx/releases/latest" | trim | base -}}
".docker/cli-plugins/docker-buildx":
  type: file
  url: "https://github.com/docker/buildx/releases/download/{{ $dockerBuildxVersion }}/buildx-{{ $dockerBuildxVersion }}.linux-amd64"
  executable: true

# Downloads all the variants of Fira Code Nerd Font
{{ $nerdFontRevision := output "git" "ls-remote" "https://github.com/ryanoasis/nerd-fonts.git" "HEAD" | trimSuffix "HEAD\n" | trim }}
{{-   range $_, $face := list "Regular" "Light" "Medium" "Bold" "Retina" "SemiBold" -}}
{{-     range $_, $variant := list "" " Mono" }}
".local/share/fonts/Fira Code {{ $face }} Nerd Font Complete{{ $variant }}.ttf":
  type: file
  url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ $nerdFontRevision }}/patched-fonts/FiraCode/{{ $face }}/complete/Fira%20Code%20{{ $face }}%20Nerd%20Font%20Complete{{ $variant | replace " " "%20" }}.ttf"
{{      end -}}
{{-   end -}}

{{- end -}}
