{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

".oh-my-zsh":
  type: archive
  url: "https://github.com/ohmyzsh/ohmyzsh/archive/{{ template "get-github-head-revision" list "ohmyzsh/ohmyzsh" $cache }}.tar.gz"
  stripComponents: 1
  # waiting for https://github.com/twpayne/chezmoi/issues/1614#issuecomment-966524408
  # exact: true

".oh-my-zsh/custom/themes/powerlevel10k":
  type: archive
  url: "https://github.com/romkatv/powerlevel10k/archive/{{ template "get-github-head-revision" list "romkatv/powerlevel10k" $cache }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-syntax-highlighting":
  type: archive
  url: "https://github.com/zsh-users/zsh-syntax-highlighting/archive/{{ template "get-github-head-revision" list "zsh-users/zsh-syntax-highlighting" $cache }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-autosuggestions":
  type: archive
  url: "https://github.com/zsh-users/zsh-autosuggestions/archive/{{ template "get-github-head-revision" list "zsh-users/zsh-autosuggestions" $cache }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-completions":
  type: archive
  url: "https://github.com/zsh-users/zsh-completions/archive/{{ template "get-github-head-revision" list "zsh-users/zsh-completions" $cache }}.tar.gz"
  stripComponents: 1
  exact: true

".local/bin/direnv":
  type: file
  url: "https://github.com/direnv/direnv/releases/download/v{{ template "get-github-latest-version" list "direnv/direnv" $cache }}/direnv.linux-{{ .chezmoi.arch }}"
  executable: true

".local/bin/kubectx":
  type: file
  url: "https://github.com/ahmetb/kubectx/raw/{{ template "get-github-head-revision" list "ahmetb/kubectx" $cache }}/kubectx"
  executable: true

".oh-my-zsh/custom/plugins/my-completions/_kubectx.zsh":
  type: file
  url: "https://github.com/ahmetb/kubectx/raw/{{ template "get-github-head-revision" list "ahmetb/kubectx" $cache }}/completion/_kubectx.zsh"

".local/bin/kubens":
  type: file
  url: "https://github.com/ahmetb/kubectx/raw/{{ template "get-github-head-revision" list "ahmetb/kubectx" $cache }}/kubens"
  executable: true

".oh-my-zsh/custom/plugins/my-completions/_kubens.zsh":
  type: file
  url: "https://github.com/ahmetb/kubectx/raw/{{ template "get-github-head-revision" list "ahmetb/kubectx" $cache }}/completion/_kubens.zsh"

{{ $openSslVersion := "1.1" }}
{{ if semverCompare ">=22.04" .chezmoi.osRelease.versionID }}
{{   $openSslVersion = "3.0" }}
{{ end }}
".volta/bin":
  type: archive
  url: "https://github.com/volta-cli/volta/releases/download/v{{ template "get-github-latest-version" list "volta-cli/volta" $cache }}/volta-{{ template "get-github-latest-version" list "volta-cli/volta" $cache }}-linux-openssl-{{ $openSslVersion }}.tar.gz"

{{ if not .is_devcontainer -}}
{{   if .is_gnome -}}
".local/share/nautilus-python/extensions/code-nautilus.py":
  type: file
  url: "https://raw.githubusercontent.com/harry-cpp/code-nautilus/{{ template "get-github-head-revision" list "harry-cpp/code-nautilus" $cache }}/code-nautilus.py"

{{      if not .is_wsl -}}
".local/bin/gnome-shell-extension-installer":
  type: file
  url: "https://raw.githubusercontent.com/brunelli/gnome-shell-extension-installer/{{ template "get-github-head-revision" list "brunelli/gnome-shell-extension-installer" $cache }}/gnome-shell-extension-installer"
  executable: true
{{-     end }}

{{-   end }}

".deno/bin":
  type: archive
  url: "https://github.com/denoland/deno/releases/download/v{{ template "get-github-latest-version" list "denoland/deno" $cache }}/deno-x86_64-unknown-linux-gnu.zip"
  include:
    - deno

".docker/cli-plugins/docker-compose":
  type: file
  url: "https://github.com/docker/compose/releases/download/v{{ template "get-github-latest-version" list "docker/compose" $cache }}/docker-compose-linux-x86_64"
  executable: true

".docker/cli-plugins/docker-buildx":
  type: file
  url: "https://github.com/docker/buildx/releases/download/v{{ template "get-github-latest-version" list "docker/buildx" $cache }}/buildx-v{{ template "get-github-latest-version" list "docker/buildx" $cache }}.linux-amd64"
  executable: true

# Downloads all the variants of Fira Code Nerd Font
{{-   range $_, $face := list "Regular" "Light" "Medium" "Bold" "Retina" "SemiBold" -}}
{{-     range $_, $variant := list "" " Mono" }}
".local/share/fonts/Fira Code {{ $face }} Nerd Font Complete{{ $variant }}.ttf":
  type: file
  url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ template "get-github-head-revision" list "ryanoasis/nerd-fonts" $cache }}/patched-fonts/FiraCode/{{ $face }}/complete/Fira%20Code%20{{ $face }}%20Nerd%20Font%20Complete{{ $variant | replace " " "%20" }}.ttf"
{{      end -}}
{{-   end -}}

{{- template "save-versions-and-revisions-cache" $cache -}}

{{- end -}}
