{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

"usr/share/keyrings/docker-archive-keyring.gpg":
  type: file
  url: "https://download.docker.com/linux/{{ .chezmoi.osRelease.id }}/gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/git-core-ppa-archive-keyring.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE1DD270288B4E6030699E45FA1715D88E1DF1F24"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ if .is_gnome }}
"usr/share/keyrings/vscode-archive-keyring.gpg":
  type: file
  url: "https://packages.microsoft.com/keys/microsoft.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/google-chrome-archive-keyring.gpg":
  type: file
  url: "https://dl.google.com/linux/linux_signing_key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]
{{ end }}

"usr/local/bin/docker-compose":
  type: file
  {{ $composeVersion := includeTemplate "get-github-latest-version" (list "docker/compose-switch" $cache) }}
  url: "https://github.com/docker/compose-switch/releases/download/v{{ $composeVersion }}/docker-compose-linux-{{ .chezmoi.arch }}"
  executable: true

"usr/local/bin/git-lfs":
  type: archive-file
  {{ $gitLfsVersion := includeTemplate "get-github-latest-version" (list "git-lfs/git-lfs" $cache) }}
  url: "https://github.com/git-lfs/git-lfs/releases/download/v{{ $gitLfsVersion }}/git-lfs-linux-{{ .chezmoi.arch }}-v{{ $gitLfsVersion }}.tar.gz"
  stripComponents: 1
  path: git-lfs

{{ $dockerCredVersion := includeTemplate "get-github-latest-version" (list "docker/docker-credential-helpers" $cache) }}
{{ $gcmVersion := includeTemplate "get-github-latest-version" (list "GitCredentialManager/git-credential-manager" $cache) }}
{{ if .is_wsl }}
"usr/bin/docker-credential-wincred.exe":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ $dockerCredVersion }}/docker-credential-wincred-v{{ $dockerCredVersion }}.windows-{{ .chezmoi.arch }}.exe"
  executable: true

"usr/local/share/gcm":
  type: archive
  url: "https://github.com/GitCredentialManager/git-credential-manager/releases/download/v{{ $gcmVersion }}/gcm-win-x86-{{ $gcmVersion }}.zip"
  exact: true
{{ else }}
"usr/local/share/gcm":
  type: archive
  url: "https://github.com/GitCredentialManager/git-credential-manager/releases/download/v{{ $gcmVersion }}/gcm-linux_{{ .chezmoi.arch }}.{{ $gcmVersion }}.tar.gz"
  exact: true

{{   if .is_gnome }}
"usr/bin/docker-credential-secretservice":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ $dockerCredVersion }}/docker-credential-secretservice-v{{ $dockerCredVersion }}.linux-{{ .chezmoi.arch }}"
  executable: true
{{   end }}
{{ end }}

{{ template "save-versions-and-revisions-cache" $cache -}}
