{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

"usr/share/keyrings/docker-archive-keyring.gpg":
  type: file
  url: "https://download.docker.com/linux/{{ .chezmoi.osRelease.id }}/gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/kubic-archive-keyring.gpg":
  type: file
  url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ .chezmoi.osRelease.versionID }}/Release.key"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/git-core-ppa-archive-keyring.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE1DD270288B4E6030699E45FA1715D88E1DF1F24"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ if .is_gnome }}
"usr/share/keyrings/vscode-archive-keyring.gpg":
  type: file
  url: "https://packages.microsoft.com/keys/microsoft.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/google-chrome-archive-keyring.gpg":
  type: file
  url: "https://dl.google.com/linux/linux_signing_key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ if eq .chezmoi.osRelease.versionCodename "bionic" }}
"usr/share/keyrings/communitheme-ppa-archive-keyring.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xDEE9D5E11727231736FD173F03D12CDECFB24D48"
  filter:
    command: gpg
    args: ["--dearmor"]
{{ end }}
{{ end }}

"usr/local/bin/docker-compose":
  type: file
  url: "https://github.com/docker/compose-switch/releases/download/v{{ template "get-github-latest-version" list "docker/compose-switch" $cache }}/docker-compose-linux-{{ .chezmoi.arch }}"
  executable: true

{{ if .is_wsl }}
"usr/bin/docker-credential-wincred.exe":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ template "get-github-latest-version" list "docker/docker-credential-helpers" $cache }}/docker-credential-wincred-v{{ template "get-github-latest-version" list "docker/docker-credential-helpers" $cache }}-{{ .chezmoi.arch }}.zip"
  executable: true
  filter:
    command: zcat

"usr/local/share/gcm-core":
  type: archive
  url: "https://glare.vercel.app/GitCredentialManager/git-credential-manager@v{{ template "get-github-latest-version" list "GitCredentialManager/git-credential-manager" $cache }}/gcmcore-win-x86.+.zip$"
  exact: true
{{ else }}
"usr/bin/docker-credential-secretservice":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ template "get-github-latest-version" list "docker/docker-credential-helpers" $cache }}/docker-credential-secretservice-v{{ template "get-github-latest-version" list "docker/docker-credential-helpers" $cache }}-{{ .chezmoi.arch }}.tar.gz"
  executable: true
  filter:
    command: tar
    args: ["-xzOf-"]

"usr/local/share/gcm-core":
  type: archive
  url: "https://glare.vercel.app/GitCredentialManager/git-credential-manager@v{{ template "get-github-latest-version" list "GitCredentialManager/git-credential-manager" $cache }}/gcmcore-linux_amd64.+.tar.gz$"
  exact: true
{{ end }}

{{ template "save-versions-and-revisions-cache" $cache -}}
